ls1intum/artemis-ios-core-modules

- Sources/SharedModels/Course.swift
- Sources/SharedModels/Exam/Exam.swift
- Sources/SharedModels/Exam/ExerciseGroup.swift
- Sources/SharedModels/Exercise/BaseExercise.swift
- Sources/SharedModels/Exercise/FileUploadExercise.swift
- Sources/SharedModels/Exercise/Grading/GradingCriterion.swift
- Sources/SharedModels/Exercise/Grading/GradingInstruction.swift
- Sources/SharedModels/Exercise/ModelingExercise.swift
- Sources/SharedModels/Exercise/Participation/TemplateParticipation.swift
- Sources/SharedModels/Exercise/ProgrammingExercise.swift
- Sources/SharedModels/Exercise/QuizExercise.swift
- Sources/SharedModels/Exercise/Submission/Feedback.swift
- Sources/SharedModels/Exercise/Submission/Result.swift
- Sources/SharedModels/Exercise/TextExercise.swift
- Sources/SharedModels/Exercise/UnknownExercise.swift
- Sources/SharedModels/User/Account.swift
Involves changes required to integrate the shared models into Themis.
> Model adjustments for Themis

- .swiftlint.yml
- Package.resolved
- Package.swift
- Sources/APIClient/APIClient.swift
- Sources/APIClient/HTTPStatusCode.swift
- Sources/APIClient/StompClient/ArtemisStompClient.swift
- Sources/Account/Services/AccountService/AccountService.swift
- Sources/Account/ViewModels/AccountNavigationBarMenuViewModel.swift
- Sources/DesignLibrary/Colors.swift
- Sources/DesignLibrary/Paddings.swift
- Sources/Login/Services/LoginService/LoginServiceImpl.swift
- Sources/PushNotifications/PushNotificationEncrypter.swift
- Sources/PushNotifications/PushNotificationHandler.swift
- Sources/SharedModels/Course.swift
- Sources/SharedModels/Exercise/ProgrammingExercise.swift
- Sources/SharedModels/Exercise/QuizExercise.swift
- Sources/SharedModels/Exercise/Submission/Result.swift
- Sources/SharedModels/Language.swift
- Sources/SharedModels/TutorialGroup.swift
- Sources/SharedModels/User/Account.swift
Add Websocket Stomp client
change that user is already loaded on login instead by account view
minor changes to models
Changes can be tested with Artemis iOS app on branch: origin/feature/message-socket
> Web socket client

- Sources/DesignLibrary/ArtemisWebView.swift
improve scrolling and loading behaviour for webview
> improve scrolling and loading behaviour for webview

- Sources/DesignLibrary/ArtemisWebView.swift
This PR fixes a bug that prevents ArtemisWebView from calculating its height correctly when its width changes. 
Here's a demo of the issue:
https://github.com/ls1intum/artemis-ios-core-modules/assets/22798314/42a6df32-71c5-465f-81aa-91ff3021a41d
The fix adds an optional `customJSHeightQuery` property that allows the parent view to control how ArtemisWebView determines it's height. An example usage can be see in Themis, where for rendering the standalone problem statement I use the following value for `customJSHeightQuery`: `document.body.getElementsByClassName('instructions__content')[0].scrollHeight`
Here's a demo after the fix:
https://github.com/ls1intum/artemis-ios-core-modules/assets/22798314/65824beb-ab2d-4891-bb21-01c9ab7eef0f
If the provided `customJSHeighQuery` is incorrect …
> Bugfix: ArtemisWebView can't set it's height correctly when its width changes

- Sources/SharedModels/Exercise/Submission/TextSubmission.swift
This PR contains changes to support text exercises on Themis. I tried to keep the changes minimal and non-breaking as much as possible.
> Text exercise changes

- Sources/SharedModels/Exercise/Submission/FileUploadSubmission.swift
This PR involves some changes required to support file exercise assessments in Themis
> File upload exercise integration

- Sources/SharedModels/Exercise/Submission/Feedback.swift
- Sources/SharedModels/Exercise/Submission/ProgrammingExerciseTestCase.swift
This PR is an adaptation for the change implemented in: https://github.com/ls1intum/Artemis/pull/7015
> `Programming Exercise`: Add test case to feedback model

- README.md
- Sources/SharedModels/Exam/Exam.swift
- Sources/SharedModels/Exercise/BaseExercise.swift
- Sources/SharedModels/Exercise/FileUploadExercise.swift
- Sources/SharedModels/Exercise/ModelingExercise.swift
- Sources/SharedModels/Exercise/ProgrammingExercise.swift
- Sources/SharedModels/Exercise/QuizExercise.swift
- Sources/SharedModels/Exercise/Submission/BaseSubmission.swift
- Sources/SharedModels/Exercise/Submission/FileUploadSubmission.swift
- Sources/SharedModels/Exercise/Submission/ModelingSubmission.swift
- Sources/SharedModels/Exercise/Submission/ProgrammingSubmission.swift
- Sources/SharedModels/Exercise/Submission/QuizSubmission.swift
- Sources/SharedModels/Exercise/Submission/TextSubmission.swift
- Sources/SharedModels/Exercise/Submission/UnknownSubmission.swift
- Sources/SharedModels/Exercise/TextExercise.swift
- Sources/SharedModels/Exercise/UnknownExercise.swift
This PR involves some changes required to support multiple correction rounds in Themis.
> `Exam mode`: Correction round changes

- Sources/DesignLibrary/DataStateView.swift
| as-is | vision |
|-|-|
| ![Simulator Screenshot - iPhone 15 Pro - 2023-12-07 at 15 28 11](https://github.com/ls1intum/artemis-ios-core-modules/assets/23535000/10fe8855-9ddf-4ccd-b0d4-106a8b9bc17b) | ![Simulator Screenshot - iPhone 15 Pro - 2023-12-07 at 15 25 36](https://github.com/ls1intum/artemis-ios-core-modules/assets/23535000/483935fc-9242-4d94-a957-395643a7ac2f) |
> `General`: Improve the usability of data state failures

- Sources/PushNotifications/Models/PushNotification.swift
- Sources/PushNotifications/Models/PushNotificationSetting.swift
- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
- Sources/PushNotifications/ViewModels/PushNotificationSettingsViewModel.swift
- Sources/PushNotifications/Views/PushNotificationSettingsView.swift
Closes https://github.com/ls1intum/artemis-ios/issues/60
| exam | user mention|
|-|-|
| ![Simulator Screenshot - iPhone 15 Pro - 2023-12-31 at 00 26 20](https://github.com/ls1intum/artemis-ios-core-modules/assets/23535000/db30e09b-6ab2-457a-8ecb-63e025ad6246) | ![Simulator Screenshot - iPhone 15 Pro - 2023-12-31 at 00 26 32](https://github.com/ls1intum/artemis-ios-core-modules/assets/23535000/4d222d33-122b-463a-a7eb-e13ca51c9276) |
| exam | user mention|
|-|-|
| ![Simulator Screenshot - iPhone 15 Pro - 2023-12-12 at 22 21 43](https://github.com/ls1intum/artemis-ios-core-modules/assets/23535000/e9cd62b1-a7a1-4c62-92dd-758a1d5c4906) | ![Simulator Screenshot - iPhone 15 Pro - 2023-12-12 at 22 21 48](https://github.com/ls1intum/artemis-ios-core-modules/assets/23535000/27ed1b43-90c6-4258-82f2-0 …
> `Communication`: Add notification settings

- Sources/SharedModels/Course/CoursesForDashboard.swift
- Sources/SharedServices/CourseService/CourseService.swift
- Sources/SharedServices/CourseService/CourseServiceImpl.swift
> `General`: Improve dashboard performance

- Sources/DesignLibrary/Colors.swift
- Sources/DesignLibrary/ProgressBar.swift
- Sources/SharedModels/Course/CourseForDashboardDTO.swift
- Sources/SharedModels/Course/CourseScore.swift
- Public default initializers for `CourseForDashboardDTO`, `CourseScore`, and `StudentScore`
- Color placeholder gray if total progress is 0
> `Courses`: Improve statistics coloring

- Sources/ArtemisMarkdown/RegexReplacementVisitor.swift
- Sources/DesignLibrary/Colors.swift
- Sources/DesignLibrary/ProgressBar.swift
- Sources/SharedModels/Course/CourseForDashboardDTO.swift
- Sources/SharedModels/Course/CourseScore.swift
- Sources/SharedModels/Exercise/BaseExercise.swift
- Sources/SharedModels/Exercise/FileUploadExercise.swift
- Sources/SharedModels/Exercise/ModelingExercise.swift
- Sources/SharedModels/Exercise/Participation/ProgrammingExerciseStudentParticipation.swift
- Sources/SharedModels/Exercise/ProgrammingExercise.swift
- Sources/SharedModels/Exercise/QuizExercise.swift
- Sources/SharedModels/Exercise/TextExercise.swift
- Sources/SharedModels/Exercise/UnknownExercise.swift
- Public default initializers for `CourseForDashboardDTO`, `CourseScore`, and `StudentScore`
- Employ Markdown mention scheme
- **Breaking**: Changed `ProgrammingExerciseStudentParticipation` retain type: value
- **Breaking**: Renamed `IncludedInOverallScore.includedCompletly`: includedCompletely
- Color placeholder gray if total progress is zero
> `Development`: Release 10.0.0

- Package.resolved
- Package.swift
SwiftLint 0.55.0 breaks the plugin name, see https://github.com/realm/SwiftLint/compare/0.54.0...0.55.0
> `Development`: Fix SwiftLint

- Package.resolved
- Package.swift
- Sources/SharedModels/Course/Course.swift
- Add `numberOfLectures` helper attribute
- **Breaking**: Fix SwiftLint dependency resolution
- Fix SwiftStomp dependency resolution
> `Development`: Release 11.0.0

- Sources/ArtemisMarkdown/RegexReplacementVisitor.swift
- Tests/ArtemisMarkdownTests/ArtemisMarkdownTests.swift
> `Communication`: Match mentions

- Sources/SharedModels/Course/Course.swift
- Sources/SharedModels/Exercise/Participation/ProgrammingExerciseStudentParticipation.swift
- Sources/SharedModels/Exercise/ProgrammingExercise.swift
- Sources/SharedModels/Exercise/Stats/ExerciseStatistics.swift
- Sources/SharedModels/Exercise/Stats/ExerciseStatsForAssessmentDashboard.swift
- Sources/SharedModels/Exercise/Submission/ProgrammingSubmission.swift
- Sources/SharedModels/Exercise/Submission/Result.swift
- Sources/SharedServices/ExerciseService/ExerciseService.swift
- Sources/SharedServices/ExerciseService/ExerciseServiceStub.swift
For taking Screenshots in Themis, we need a bit more mock data, such as Programming Exercise submissions. This PR adds the necessary data.
> Add mock models for Themis screenshots

- Sources/SharedModels/Course/Course.swift
- Sources/SharedModels/Exercise/TextExercise.swift
In order to take automatic screenshots of the Text Exercise Assessment View, we need a mock Text Exercise in our Mock Course.
> Add text exercise for Themis mock data

- README.md
- Sources/SharedModels/Exercise/ProgrammingExercise.swift
Fix error:
```
18:46:23.356 ❤️ ERROR APIClient.sendRequest():151 - dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "courses", intValue: nil), _JSONKey(stringValue: "Index 33", intValue: 33), CodingKeys(stringValue: "course", intValue: nil), CodingKeys(stringValue: "exercises", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "programmingLanguage", intValue: nil)], debugDescription: "Cannot initialize ProgrammingLanguage from invalid String value JAVASCRIPT", underlyingError: nil))
```
> `Lectures`: Add JavaScript programming language

- Sources/APIClient/APIClient.swift
- Sources/PushNotifications/Models/PushNotification.swift
- Sources/SharedModels/Course/CoursesForDashboardDTO.swift
- Sources/SharedModels/Exercise/Submission/Result.swift
- Sources/SharedModels/Exercise/Submission/TextSubmission.swift
- Sources/SharedModels/User/Account.swift
- Sources/UserStore/UserSession.swift
- Sources/UserStore/UserSessionFactory.swift
We currently have quite a few SwiftLint warnings that can be resolved. This PR aims to resolve all warnings that are not related to a "TODO" warning.
> Fix SwiftLint warnings

- Package.swift
- Update SwiftStomp
- Remove Scarscream since it isn't used anymore
> `Development`: Update SwiftStomp

- Sources/SharedModels/Faq/FaqDTO.swift
- Sources/SharedModels/Faq/FaqState.swift
For implementing FAQs, we need the corresponding DTOs
> `FAQ`: Add FAQ types

- Sources/SharedModels/Faq/FaqDTO.swift
- Sources/SharedModels/Faq/FaqState.swift
FAQs have an faqState attribute
> `FAQ`: Update faqState attribute

- Sources/ArtemisMarkdown/ArtemisImageProvider.swift
- Sources/ArtemisMarkdown/ArtemisMarkdown.swift
- Sources/ArtemisMarkdown/RegexReplacementVisitor.swift
We can only render images from the bundle currently, but we also need web images. This PR adds support for them.
> `Markdown`: Render images

- Package.swift
- Sources/ArtemisMarkdown/ArtemisImageProvider.swift
- Sources/ArtemisMarkdown/String+MarkdownImage.swift
- Sources/PushNotifications/Models/PushNotification.swift
1. Add helper function to show placeholders instead of the image markdown in notifications
2. Add helper function to display all images as block images
3. Set max height for images
4. Use ArtemisAsyncImage for loading indicator
5. Fix upside down images
> `General`: Improve display of images

- Sources/ArtemisMarkdown/ArtemisImageProvider.swift
- Sources/ArtemisMarkdown/ZoomableImagePreview.swift
Add support for viewing images full screen and zooming
<video src="https://github.com/user-attachments/assets/93fe41ba-d871-4d2a-a7ff-da16cbb81e93">
> `Markdown`: Add zoomable image previews

- Sources/PushNotifications/PushNotificationHandler.swift
- Sources/PushNotifications/Services/PushNotificationService/PushNotificationServiceImpl.swift
> `Notifications`: Add support for app extension notifications

- Sources/PushNotifications/Models/PushNotification.swift
Fixes https://github.com/ls1intum/artemis-ios/issues/252
> `Notification`: Correct new conversation reply notification type

- Sources/PushNotifications/Models/PushNotification+Communication.swift
- Sources/PushNotifications/Models/PushNotification.swift
- Sources/PushNotifications/PushNotificationHandler+Communication.swift
- Sources/PushNotifications/PushNotificationHandler.swift
- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
See https://github.com/ls1intum/artemis-ios/pull/256
> `Notifications`: Support communication notifications

- Sources/APIClient/APIClient.swift
- Sources/PushNotifications/PushNotificationHandler.swift
- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
Adds a notification for when a user's login session expires.
https://github.com/ls1intum/artemis-ios/issues/277
> `Notifications`: Add notification for session expired

- Sources/PushNotifications/Models/PushNotification+Communication.swift
- Sources/PushNotifications/PushNotificationHandler.swift
- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
- Add `courseId` to CommunicationInfo
- Add `categoryIdentifier` for Communication notifications
- Add `registerNotificationCategories` function
> `Notifications`: Add support for quick reply

- Sources/Login/Services/LoginService/LoginServiceImpl.swift
- Sources/PushNotifications/PushNotificationHandler+Communication.swift
- Sources/PushNotifications/Services/PushNotificationService/PushNotificationServiceImpl.swift
- Sources/SharedServices/AccountService/AccountServiceImpl.swift
- Sources/SharedServices/CourseService/CourseServiceImpl.swift
- Sources/SharedServices/ExerciseService/ExerciseServiceImpl.swift
Adapts REST endpoints to match Artemis 8.0.0
> `General`: Adapt REST endpoints

- Sources/APIClient/APIClient.swift
- Sources/Login/Models/PasskeyChallenge.swift
- Sources/Login/Models/PasskeyCredential.swift
- Sources/Login/Resources/en.lproj/Localizable.strings
- Sources/Login/Services/LoginService/LoginService.swift
- Sources/Login/Services/LoginService/LoginServiceImpl.swift
- Sources/Login/ViewModels/LoginViewModel+Passkey.swift
- Sources/Login/ViewModels/LoginViewModel.swift
- Sources/Login/ViewModels/PasskeySetupViewModel.swift
- Sources/Login/Views/LoginView.swift
- Sources/PushNotifications/PushNotificationHandler+Communication.swift
- Sources/UserStore/UserSession.swift
This PR adds support for logging in with passkeys as well as creating new passkeys.
https://github.com/user-attachments/assets/4919f4b8-f4f8-4593-b48f-6b9fc8822bb0
> `Login`: Add support for passkeys

- Sources/SharedModels/Exercise/BaseExercise.swift
- Sources/SharedModels/Resources/en.lproj/Localizable.strings
Reverts ls1intum/artemis-ios-core-modules#145
> Revert "`Exercises`: Add computed property for status"

- Sources/PushNotifications/PushNotificationHandler+Communication.swift
Since the Login Mechanism is changed to support passkeys and this was already implemented for loading profile pictures, we still need support for the legacy mechanism temporarily (4 weeks). After this period, this PR can be reverted.
> `Notifications`: Ensure profile pics work with old login

- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
- Sources/PushNotifications/Services/PushNotificationService/PushNotificationService.swift
- Sources/PushNotifications/Services/PushNotificationService/PushNotificationServiceImpl.swift
- Sources/PushNotifications/ViewModels/NotificationSettingsViewModel.swift
- Sources/PushNotifications/Views/NotificationSettingsView.swift
With this PR, we add the functionality to select from notification presets.
https://github.com/user-attachments/assets/4909c2aa-4782-4777-b12a-85da6c8385a8
We also add a small disclaimer for email notifications
> `Notifications`: Support setting presets

- Sources/PushNotifications/Models/General/ExerciseOpenForPracticeNotification.swift
- Sources/PushNotifications/Models/General/ExerciseUpdatedNotification.swift
- Sources/PushNotifications/Models/General/NewExerciseNotification.swift
- Sources/PushNotifications/Models/General/QuizExerciseStartedNotification.swift
- Sources/PushNotifications/Models/PushNotification+Communication.swift
- Sources/PushNotifications/PushNotificationHandler+Communication.swift
- Sources/SharedModels/Faq/FaqDTO.swift
Resolve SwiftLint warnings and remove unused types in notifications
> `General`: Clean up swiftlint warnings

- Sources/Account/Services/PasskeyService.swift
- Sources/Account/Services/PasskeyServiceImpl.swift
- Sources/Account/ViewModels/PasskeySettingsViewModel.swift
- Sources/Account/Views/PasskeySettingsView.swift
This PR adds a swipe action in passkey settings to remove passkeys
> `Login`: Allow deleting passkeys
