ls1intum/artemis-ios-core-modules

- Sources/DesignLibrary/ArtemisWebView.swift
I've noticed that the webview can't set it's height property correctly when the loading takes too long (more than 2 seconds). This affects users having slow connection speeds.
What I did:
- Added a timer that does the following:
- Starts firing after the `webView(..didFinish navigation: )` is called
- Checks every 0.5 seconds for `document.readyState` to be set
- If set, it starts sampling the `document.body.scrollHeight` value. The sampling occurs 5 times with an interval of 1 seconds. 
This makes the webview start displaying content as it arrives, expanding its height
----
@sven0311  I noticed your latest commit also addresses this issue with clicks and preserved your implementation as well. With this PR both timer-based and click-based height adjustments should work fine. 🙂
> Bugfix: Wrong ArtemisWebView height when the connection speed is slow

- Sources/SharedModels/CourseForDashboard.swift
Changes:
- Create a new DTO struct called `ParticipationResultDTO` 
- Change the type of `participationResults` from `Result` to `ParticipationResultDTO` in `CourseForDashboard` model. 
This is required because of the changes introduced in this Artemis PR: https://github.com/ls1intum/Artemis/pull/6984
> `Endpoint Change`: Replace Result with ParticipationResultDTO in CourseForDashboard

- Sources/SharedModels/Exercise/Submission/ModelingSubmission.swift
This PR adds 2 optional fields to ModelingSubmissions:
- model
- explanationText
This change is required because Themis now supports modeling exercises.
> `Modeling Exercises`: Add optional model and explanationText fields to ModelingSubmission

- Sources/SharedModels/Exercise/BaseExercise.swift
- Sources/SharedModels/Exercise/Stats/DueDateStat.swift
Modified the `hash(into:)` and `==` functions of `Exercise` to also consider some date and assessment-related fields.
This is useful for cases when, for example, an array of exercises are passed to a  `ForEach` element. Previously, `ForEach` differentiated elements based on `id`, and this led to issues where a change to an exercise deadline or title was not immediately reflected on the UI.
> Hashable conformance adjustments for the Exercise model

- Package.swift
This PR fixes a build problem that originated from a dependency named Starscream. Starscream is not a direct dependency of ArtemisCore but a dependency of SwiftStomp, which is used for communication-related features in ArtemisCore. You can see a screenshot of the error below:
> `Fix`: Starscream build issue

- Package.swift
This PR reverts #15 since it did not produce the desired effect. When ArtemisCore is imported as a non-local dependency, Xcode still fetches the latest version of Starscream, ignoring the exact version specified in the `Package` file.
> Revert Starscream dependency fix

- README.md
- Sources/Account/Views/AccountNavigationBarMenuView.swift
- Sources/Login/Views/InstitutionSelectionView.swift
- Sources/SharedModels/Course.swift
> `Communication`: Code of conduct

- README.md
- Sources/APIClient/HTTPMethod.swift
`UPDATE` becomes `PATCH` because the former does not exist as a HTTP request method [[1](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH)]
Alternatively, we could use the newly released [Swift HTTP Types](https://github.com/ls1intum/artemis-ios-core-modules/pull/22#swift-http-types) library.
> `Development`: Fix HTTP method

- README.md
- Sources/ProfileInfo/Model/ProfileInfo.swift
Some test servers use a local VC & CI setup, i.e.:
- artemis-test3.artemis.cit.tum.de
- artemis-test6.artemis.cit.tum.de
Previously, an iOS client could not log in to these test servers because of a decoding error:
```
"No value associated with key CodingKeys(string Value: \"buildPlanURLTemplate\", intValue: nil) (\"buildPlanURLTemplate\")."
```
> `Development`: Fix could not decode ProfileInfo's buildPlanURLTemplate

- Package.resolved
- README.md
- Sources/Account/ViewModels/AccountNavigationBarMenuViewModel.swift
Closes https://github.com/ls1intum/ArtemisExamChecker/issues/14
Previously, a user could not log out if the current notification device configuration was unavailable (for any reason).
> `General`: Fix logout if device notification configuration is unavailable

- Sources/SharedModels/Exercise/Stats/ExerciseStatsForAssessmentDashboard.swift
This PR adds a new `numberOfAssessmentsOfCorrectionRounds` to `ExerciseStatsForAssessmentDashboard`. The change is required by Themis to show the assessment statistic for exercises in the second correction round of an exam.
> `Exercise Stats`: Add number of assessments of correction rounds

- Sources/DesignLibrary/ArtemisButtonStyle.swift
This PR adds a custom initializer for the Artemis Button Style to allow changing the color of the button.
> `Buttons`: Add Custom Init for the Artemis Button Style

- Sources/SharedModels/Exercise/ModelingExercise.swift
This PR adds BPMN as a diagram type to the modeling exercise shared models. It fixes a bug that shows an error on the dashboard screen.
> `Modeling Exercises`: Add BPMN case to Shared Models

- Sources/SharedModels/Course/Course.swift
`api/courses/for-dashboard` does not return `lectures` data, but `api/courses/\(courseId)/for-dashboard` does.
Add `numberOfLectures` to display it in the dashboard.
Ref.: [course.model.ts](https://github.com/ls1intum/Artemis/blob/4eb01fd95356dea74cc5b10b601d98fa69fab5d0/src/main/webapp/app/entities/course.model.ts)
> `Courses`: Add `numberOfLectures` helper attribute

- Sources/PushNotifications/Views/PushNotificationSetupView.swift
Currently, the image on `PushNotificationSetupView` is sized using `UIScreen.main.bounds.width * 0.8`. While this works on iPhone, it doesn't work on iPad. This view gets shown inside a sheet on the iPad, which is not full width. Therefore, the width that gets set is wider than the sheet itself, which leads to text being cut off (see screenshot).
By using `containerRelativeFrame`, we can make the Image span a maximum of 80% of the available width, which is what the original code intended.
> `Notifications`: Fix size of PushNotificationSetupView

- Sources/SharedModels/Exercise/ProgrammingExercise.swift
With [Artemis#8802](https://github.com/ls1intum/Artemis/pull/8802), there will be an option to create programming exercises with Rust as the programming language. We need to support this as well to make sure decoding server responses doesn't fail.
> `Exercises`: Add Rust programming language

- Sources/SharedModels/Conversation/Channel.swift
The web app uses a megaphone icon for announcement channels, with this PR we ensure consistency between it and the iOS app.
> `Communication`: Use megaphone instead of bell for announcement channel

- Sources/PushNotifications/Views/PushNotificationSettingsView.swift
Currently, the user can edit some of the Push Notification Settings and then (maybe on accident) dismiss the sheet by swiping down. Changes are not saved in this case, which may be confusing since the toggle has already switched state.
Swiping down to dismiss the sheet is only available as long as the user has not changed any notification settings. As soon as a change has been made that could be saved, dismissing the sheet by swiping is no longer possible. Users need to take explicit action by either pressing on Cancel or Save to make their intent clear.
> `Notifications`: Prevent dismissing PushNotificationSettings with unsaved changes

- Sources/SharedModels/Exercise/ExerciseDetailsDTO.swift
- Sources/SharedServices/ExerciseService/ExerciseServiceImpl.swift
Due to changes in [Artemis#8712](https://github.com/ls1intum/Artemis/pull/8712), decoding responses to `/api/exercises/:id/details` fail because the structure of the response has changed. We get a new ExerciseDetailsDTO instead of an Exercise.
This leads to decoding failures in the app when opening notifications or pulling to refresh on an exercise.
> `Exercises`: Fix decoding failure for Exercise Details

- Sources/SharedModels/Exercise/ProgrammingExercise.swift
Currently, whenever support for a new Programming Language is added to Artemis, the iOS app will fail to load the entire dashboard or any course if an exercise with that new language exists. Therefore, no course can be accessed at all until support for the new language has been added. The reason for this is that we cannot decode any server response that contains an exercise with unknown programming language.
By adding an `unknown` case to our Programming Languages, we can ensure that this issue does not occur when new languages are added in the future. The iOS Apps continue to function with existing languages.
- "JAVA" decodes to `.java`
- "C" decodes to `.c`
- "PYTHON" decodes to `.python`
- "JULIA" decodes to `.unknown` (we don't have an enum case for it)
> `Exercises`: Prevent decoding failures for future new programming language constants

- Sources/SharedModels/Course/Course.swift
With [this PR of Artemis](https://github.com/ls1intum/Artemis/pull/8801), Courses can choose the following options for messaging:
- Disabled (no communication)
- Communication only (only channels like announcement, organization …)
- Communication and messaging (channels as well as direct and group messages)
Messaging only will no longer exist.
Therefore, we remove the `messagingOnly` option.
> `Communication` **Breaking**: Merge Messaging and Communication

- Sources/SharedModels/Conversation/OneToOneChat.swift
Direct messages (one to one chats) currently don't have an icon.
> `Communication`: Add missing icon for DMs

- Sources/PushNotifications/PushNotificationResponseHandler.swift
Notification Targets are wrong for New Course Posts and Add/Create channel notifications. They still reference `/discussion` and `/messages` which are both now `/communication`.
> `Notifications`: Fix notification targets

- Sources/PushNotifications/Models/PushNotification.swift
- Sources/PushNotifications/PushNotificationResponseHandler.swift
newReplyForExercisePost and newReplyForLecturePost didn't work at all,
Create/Add/Remove channel did not use correct ConversationTarget
> `Notifications`: Fix incorrect targets

- Sources/PushNotifications/Models/PushNotification.swift
- Sources/PushNotifications/PushNotificationResponseHandler.swift
Exercise and Lecture Post notifications show the wrong content. We fix this.
These and reply notifications then show a "This link is not supported by the app" error. We fix this as well.
> `Notifications`: Fix wrong content and targets for lecture/exercise posts

- Sources/PushNotifications/PushNotificationResponseHandler.swift
When a user receives a Notification about a new DM, the target is missing so that he/she ends up at the error saying this link is not supported.
> `Notifications`: Add target for new DM Notifications

- Sources/DesignLibrary/FilterBarPicker.swift
We add a Filter Bar component that can potentially be used in multiple areas. We will first use it for filtering Conversations, but we can also use it for Exercises and more later.
It is customizable via the provided Filter Type which needs to conform to `FilterPicker`:
* Color for each item
* Icon for each item
* Title per item
* Conditionally hiding filters
> `DesignLibrary`: Add FilterBarPicker component

- Sources/PushNotifications/Models/PushNotification.swift
Notifications for messages and replies in Course-Wide non exercise/lecture posts were showing wrong content (date instead of message)
> `Notifications`: Fix content for Course-Wide general channel notifications

- Package.swift
- Sources/Account/Resources/en.lproj/Localizable.strings
- Sources/Account/ViewModels/AccountNavigationBarMenuViewModel.swift
- Sources/Account/Views/AccountNavigationBarMenuView.swift
- Sources/Account/Views/ProfileView.swift
- Sources/SharedModels/Conversation/ConversationUser.swift
- Sources/SharedModels/User/Account.swift
In order to add profile pictures, we need Accounts to have a `imageUrl` attribute that represents the path to the account's profile picture if available.
We also add a `imagePath` helper attribute to convert this relative path into an absolute one for use in `ArtemisAsyncImage`.
The user's profile picture is also displayed on the ProfileInfo sheet.
> `Communication`: Add profile picture support

- Sources/PushNotifications/Models/PushNotification.swift
- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
Notifications for DMs or Group DMs currently look like this:
> **New Message**
> New direct message from Anian Schleyer in course Test.
This is a bad user experience since we don't show the message content.
We change these notification to look like this:
> **New Message**
> New direct message from Anian Schleyer in course Test:
> Message Content Here
> `Communication`/`Notification`: Show message content in DM notifications

- Sources/Account/Views/AccountNavigationBarMenuView.swift
For some reason, the Account Menu for the navigation bar has a fixed width. This causes the navigation title to be offset to the left in many cases.
> `Dashboard`: Fix misaligned menu bar

- Sources/SharedModels/Conversation/ConversationUser.swift
- Sources/SharedModels/User/Account.swift
Due to some server urls being entered with a trailing slash and some without, profile images failed to load if the user was on a server with a trailing slash in its url.
> `Communication`: Fix profile pictures not being shown

- Sources/PushNotifications/Models/PushNotification.swift
- Sources/PushNotifications/Resources/en.lproj/Localizable.strings
Non course wide channel notifications are missing the message content, and author/channel names are swapped.
> `Notifications`: Fix non course wide channel message notification content

- Sources/SharedModels/Exercise/BaseExercise.swift
Exercises and thus the dashboard fail to decode if an exercise with Athena feedback exists.
> `Exercises`: Add Athena Assessment constant to fix decoding failure

- Sources/Account/ViewModels/AccountNavigationBarMenuViewModel.swift
- Sources/UserStore/UserSession.swift
When users had disabled "Remember me" on the login screen, they could not continue from the notification setup screen and thus not use the app.
> `General`: Fix users not being able to use app without "Remember me"

- Sources/SharedModels/Exercise/ProgrammingExercise.swift
This PR adds a constant for TypeScript, as seen in https://github.com/ls1intum/Artemis/pull/9440
> `Exercises`: Add typescript language constant

- Sources/SharedModels/Course/Course.swift
In order to show FAQs, we need to fetch whether a course has FAQs enabled. This PR adds the corresponding attribute to `Course`.
> `Courses`: Add faqEnabled attribute to course

- Sources/UserStore/KeychainHelper.swift
- Sources/UserStore/UserSession.swift
Keychain items are not accessible when the device is locked. But we need this, so we switch to the `afterFirstUnlock` policy instead of `whenUnlocked`.
> `General`: Fix keychain items not being accessible when device is locked

- Sources/SharedModels/Conversation/BaseConversation.swift
- Sources/SharedModels/Conversation/Channel.swift
- Sources/SharedModels/Conversation/GroupChat.swift
- Sources/SharedModels/Conversation/OneToOneChat.swift
- Sources/SharedModels/Conversation/UnknownConversation.swift
This PR replaces the icon for direct messages with the user's profile picture whenever available.
> `Communication`: *Breaking* Add profile picture to conversation icon

- Sources/APIClient/StompClient/ArtemisStompClient.swift
There are lots of crashes in Artemis iOS caused by SwiftStomp calling `self.delegate?.onConnect(swiftStomp: self, connectType: .toSocketEndpoint)`. This means there is a problem in `ArtemisStompClient.onConnect`. I've identified this as a data race issue.
> `ArtemisStompClient`: Fix data concurrency/race crash

- Sources/DesignLibrary/ProgressBar.swift
> `DesignLibrary`: Fix progress bar being messed up when at over 100%

- Sources/ArtemisMarkdown/ArtemisImageProvider.swift
This PR adds the ability to export/share/save an image with a share button in the image preview.
> `Markdown`: Add ShareLink to image preview

- Package.resolved
- Package.swift
- Sources/APIClient/StompClient/ArtemisStompClient.swift
If a message is received on the web socket with `compressed: true` header, this indicates the payload is compressed. Thus, we uncompress it using gzip.
> `StompClient`: Unzip compressed websocket messages

- Sources/APIClient/StompClient/ArtemisStompClient.swift
This PR updates the websocket decompression to check for the header `X-Compressed` and decode the data from Base64 in accordance with https://github.com/ls1intum/Artemis/pull/10087.
> `ArtemisStompClient`: Update decompression

- Sources/PushNotifications/PushNotificationHandler+Communication.swift
Show a profile picture placeholder instead of the App logo when no profile picture is available.
(Preview slightly lower quality than real thing)
> `Notifications`: Show profile picture placeholder

- Sources/PushNotifications/PushNotificationCipher.swift
- Sources/UserStore/UserSession.swift
There was an edge case where notifications failed to decrypt:
- User opens Artemis and leaves the app at some point
- User receives a notification
- iOS launches Notification extension
- Notification extension loads key and delivers notification
After some time:
- App itself is deallocated from memory
- User opens the app, thus notification encryption key is renewed
At some point later, before extension is deallocated:
- User receives notification
- Notification extension is still alive
- It tries to decrypt with the old key and therefore fails
> `Notifications`: Fix notification extension using outdated key

- Sources/ProfileInfo/Model/ProfileInfo.swift
Adds `compatibleVersions` attribute to `ProfileInfo` for use with forced/recommended mobile app updates
> `General`: Add app version compatibility to ProfileInfo

- Sources/PushNotifications/Services/PushNotificationService/PushNotificationServiceImpl.swift
In order to keep track of Artemis mobile app version usage, we add the version code to the registration.
> `Notifications`: Add version code to push notification registration

- Sources/DesignLibrary/ProfilePictureInitialsView.swift
- Sources/PushNotifications/PushNotificationHandler+Communication.swift
- Sources/SharedModels/Conversation/OneToOneChat.swift
Adds a profile picture placeholder in the conversation list for users that don't have a profile picture.
> `Communication`: Show placeholder profile pics in chat list

- Sources/ProfileInfo/FeatureAvailability/FeatureAvailability.swift
- Sources/ProfileInfo/FeatureAvailability/FeatureList.swift
This PR adds a property wrapper to support using Feature toggles.
Usage:
```swift
struct SomeView: View {
@FeatureAvailability(.courseNotifications) var notificationsEnabled
var body: some View {
if notificationsEnabled {
// New feature
} else {
// Old feature or fallback
}
}
}
```
> `General`: Add Feature toggle property wrapper

- Sources/PushNotifications/Models/Communication/NewPostNotification.swift
- Sources/PushNotifications/Models/CoursePushNotification.swift
- Sources/PushNotifications/Models/PushNotification.swift
- Sources/SharedModels/ConstantsEnum.swift
- Sources/SharedModels/Course/Course.swift
- Sources/SharedModels/Course/CourseForDashboardDTO.swift
This PR adds basic support for the new Course specific notifications:
- `CoursePushNotification`: A class to decode every type of new notification in an enum
- `NewPostNotification`: First new type of notification 
- `DisplayableNotification`: Protocol to enhance display of notifications in app
> `Notifications`: Add course notifications

- Package.swift
Due to a wrong package structure there was a build failure. this PR addresses this.
> `Chore`: Correct package structure

- Sources/UserStore/Config.swift
We want to use `artemis.tum.de` for Artemis at TUM, all other urls (like the currently used `artemis.ase.in.tum.de`) will be redirected to that.
> `General`: Change TUM Artemis URL

- Sources/PushNotifications/Models/Communication/NewAnnouncementNotification.swift
- Sources/PushNotifications/Models/Communication/NewAnswerNotification.swift
- Sources/PushNotifications/Models/Communication/NewMentionNotification.swift
- Sources/PushNotifications/Models/CoursePushNotification.swift
- Sources/PushNotifications/Models/General/AttachmentChangedNotification.swift
- Sources/PushNotifications/Models/General/ExerciseAssessedNotification.swift
- Sources/PushNotifications/Models/General/ExerciseOpenForPracticeNotification.swift
- Sources/PushNotifications/Models/General/ExerciseUpdatedNotification.swift
- Sources/PushNotifications/Models/General/NewExerciseNotification.swift
- Sources/PushNotifications/Models/General/NewManualFeedbackRequestNotification.swift
- Sources/PushNotifications/Models/General/QuizExerciseStartedNotification.swift
This PR adds the same DTOs from https://github.com/ls1intum/Artemis/pull/10597 so that we can decode all available notification types on iOS.
> `Notifications`: Add DTOs for course notification types

- Sources/UserStore/Config.swift
In https://github.com/ls1intum/Artemis/pull/10595, a new URL for the KIT Artemis instance is added. We update this for the iOS app as well
> `General`: Update KIT Artemis url

- Sources/Account/Views/AccountNavigationBarMenuView.swift
- Sources/PushNotifications/Views/PushNotificationSettingsView.swift
This PR removes the old PushNotificationSettings from the Account Menu as it is replaced by the new notification system and no longer has an effect.
PushNotificationSettingsView is kept for reference when creating the new system and should be removed afterwards.
> `Notifications`: Remove notification settings from account menu

- Sources/SharedModels/Course/Course.swift
Course icons need an `/api/core/files` prefix with Artemis version 8.0, this adds it
> `Dashboard`: Add file path prefix to course icons

- Sources/PushNotifications/PushNotificationHandler+Communication.swift
- Sources/SharedModels/Conversation/ConversationUser.swift
- Sources/SharedModels/User/Account.swift
Profile pictures could not be loaded in some cases due to double "/" in file path
> `Communication`: Fix profile pictures not loading

- Sources/SharedModels/Exercise/BaseExercise.swift
- Sources/SharedModels/Resources/en.lproj/Localizable.strings
This PR extends the exercise with status for [exercise chips PR](https://github.com/ls1intum/artemis-ios/pull/333).
> `Exercises`: Add computed property for status

- Sources/Login/Services/LoginService/LoginService.swift
- Sources/Login/Services/LoginService/LoginServiceImpl.swift
Some passkey functions were duplicated, looks like I forgot to remove them when switching branches
> `Login`: Remove duplicate passkey functions

- Sources/PushNotifications/Models/Communication/NewAnswerNotification.swift
- Sources/PushNotifications/Models/NavigatableNotification.swift
Message thread paths included the wrong post id and needed a name
> `Notifications`: Fix message thread navigation

- Sources/PushNotifications/Models/NavigatableNotification.swift
I accidentally left a hardcoded value in the link for exercise notifications, this PR fixes it
> `Notifications`: Fix exercise notification deep link

- Sources/Account/Resources/en.lproj/Localizable.strings
- Sources/Account/ViewModels/AccountNavigationBarMenuViewModel.swift
- Sources/Account/Views/AccountNavigationBarMenuView.swift
- Sources/Account/Views/PasskeyRecommendationView.swift
- Sources/Account/Views/PasskeySettingsView.swift
- Sources/Login/ViewModels/LoginViewModel.swift
- Sources/UserStore/UserSession.swift
When a user
- logs in using username + password, and
- did not set up passkeys already, and
- is using a TUM instance of Artemis (we don't support passkeys for others yet)
then we want to display a recommendation to add a passkey to their account.
> `Login`: Add recommendation screen for passkeys
